module.exports = {
	data: {
        name: "英語怪文書",
        description: "Mr.Ayada says funny document.",
    },
	async execute(interaction) {
		await interaction.reply('Takahashi, thanks for the report.\nI appreciate the fact that Group 2 was able to get together with everyone.\nHowever, ...... I’m running out of time to devote to you guys, so I’m going to write from here on out without much fleshing out and with a lot of vigor. If you don’t understand something, read it out loud again and again. If you don’t understand it when you read it alone, read it together.\n\nI don’t know if you were in a hurry to imitate Group 1, but for God’s sake, listen and respond properly.\nIt’s not about time or length. It’s about whether it’s interesting as a play or not. And I always give you assignments so that you can make an interesting play by yourselves.\nI did not give you a cut script saying, ’Use this script,’ nor did I ever tell you to write a script. I heard we were going to discuss how to handle Suzuki’s script, so I just did what I could overnight for reference. I just gave them a starting point to get an idea of the creative process. I didn’t create a script. I just cut it.\nAnd just for the record, I didn’t ask you to use Suzuki’s script or not to use it. I only asked what you wanted to do. And I expressed my readiness to respond to you whichever path you choose.\nLook. I never asked you to write a script. I was trying to teach you how to write a script (or something like it). I was giving you steps that you could work on. Cards and human storytelling. But you are ignoring the steps I gave you and going down a path I didn’t teach you.\nCan you write a script? Does it make for interesting theater? What’s with that mouth like you can write a better script than I can? Are you so sure of yourselves? Don’t you dare to think that. You’re a hundred years too early.\nDo you know why I’ve given you so many steps? Do you know why it’s so hard to make use of Suzuki’s script? Why did they cut it? You don’t even know why it makes it more interesting?');
    await interaction.followUp('You don’t understand. You don’t have to know. That’s why I have told you many times that even if you don’t understand, you should accept it and face it, because then it will become interesting. But you guys won’t do it.\nYou don’t believe me? Don’t want me? Then Group 2 will be self-study from now on. However, I will not allow you to present your own work in my class without listening to me. If you want to do it on your own, do it.\n\nI have not given up on creating a play with all the members of this course. But it is very hard on my body and mind when I put all my effort into preparing assignments and asking them questions, and I don’t receive a proper response. I feel bad that I spend so much effort on those who don’t return the money and can’t give my hands to those who do.\nPlease. Imagine. Think about it.');
	}
}